---
# Configures PowerDNS Authoritative Server zone

- name: Configure forward zones
  include_tasks: zone.yml
  with_items: "{{ powerdns_zone_forward }}"
  tags:
    - configuration

- name: Configure reverse zones
  include_tasks: zone.yml
  with_items: "{{ powerdns_zone_reverse }}"
  tags:
    - configuration

- name: Import TSIG keys
  shell: pdnsutil import-tsig-key {{ item.name }} {{ item.algorithm }} {{ item.secret }}
  with_items: "{{ powerdns_zone_tsig_keys }}"
  tags:
    - configuration
  become: true

- name: Associate domains with TSIG keys
  shell: pdnsutil set-meta {{ item.domain }} TSIG-ALLOW-DNSUPDATE {{ item.key }}
  with_items: "{{ powerdns_zone_domain_keys }}"
  tags:
    - configuration
  become: true
