---
# Installs Speedtest CLI

- name: Ensure required utilities are present
  apt:
    name:
      - curl
      - gnupg2
    state: latest
    update_cache: yes
  become: true

- name: Import GPG key
  shell:
    cmd: "curl -fsSL https://packagecloud.io/ookla/speedtest-cli/gpgkey | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/speedtest-archive-keyring.gpg --import"
    creates: "/etc/apt/trusted.gpg.d/speedtest-archive-keyring.gpg"
    warn: False
  register: gpg_key_import_output
  become: true

- name: Fix GPG key permissions
  file:
    path: "/etc/apt/trusted.gpg.d/speedtest-archive-keyring.gpg"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true
  when: gpg_key_import_output.changed

- name: Add APT repository
  copy:
    content: >-
      deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/speedtest-archive-keyring.gpg] https://packagecloud.io/ookla/speedtest-cli/debian/ {{ ansible_lsb.codename }} main
    dest: /etc/apt/sources.list.d/speedtest.list
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true

- name: Install latest version
  apt: name=speedtest state=latest update_cache=yes
  tags:
    - packages
  become: true
