---
# Installs ceph components

- name: Download cephadm
  get_url:
    url: https://github.com/ceph/ceph/raw/{{ ceph_release }}/src/cephadm/cephadm.py
    dest: /usr/sbin/cephadm
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  become: true

- name: Add ceph repo
  shell: cephadm add-repo --release {{ ceph_release }}
  args:
    creates: /etc/apt/sources.list.d/ceph.list
  become: true

- name: Install ceph components
  shell: cephadm {{ item }}
  with_items:
    - install
    - install ceph-common
  become: true

- name: Install debian package for working with ceph volumes
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - ceph-volume
    - python3-packaging
  become: true
