---
# Installs Promtail log shipping agent

- name: Create group
  group: name=promtail state=present
  become: true

- name: Create user
  user:
    name: promtail
    groups: promtail
    system: true
    shell: /bin/false
    create_home: true
    home: /etc/promtail
  become: true

- name: Create data directory
  file:
    path: "{{ promtail_data_dir }}"
    state: directory
    owner: promtail
    group: promtail
    mode: 0755
  become: true

- name: Download and install Promtail
  unarchive:
    creates: "/usr/local/bin/{{ item }}"
    src: https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/{{ item }}-{{ ansible_system | lower }}-{{ promtail_architecture }}.zip
    dest: /usr/local/bin/
    remote_src: yes
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  with_items:
    - promtail
    - logcli
  register: promtail_binaries
  become: true

- name: Rename binaries
  command: mv "/usr/local/bin/{{ item }}-{{ ansible_system | lower }}-{{ promtail_architecture }}" "/usr/local/bin/{{ item }}"
  with_items:
    - promtail
    - logcli
  when: promtail_binaries.changed
  become: true

- name: Copy service template
  template:
    src: templates/promtail.service.j2
    dest: /etc/systemd/system/promtail.service
    owner: root
    group: root
    mode: "u=rwx,g=rwx,o=rwx"
  become: true

- name: Copy configuration
  template:
    src: templates/promtail.yml.j2
    dest: /etc/promtail/promtail.yml
    owner: promtail
    group: promtail
    mode: 0640
  become: true
  notify:
    - Restart Promtail

- name: Start Promtail
  systemd: name=promtail enabled=yes state=started daemon_reload=true
  become: true
