---
# Configures Vault server

- name: Copy configuration
  template:
    src: templates/vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    owner: vault
    group: vault
    mode: 0640
  become: true
  notify:
    - Restart Vault
