---

- name: Enable secrets engine
  shell: "vault secrets enable -path {{ item.path }} {{ item.type }}"
  environment:
    VAULT_ADDR: http://127.0.0.1:8200
    VAULT_TOKEN: "{{ vault_root_token }}"
  no_log: true
  loop: "{{ vault_secrets_engines }}"
  when: item.path not in vault_enabled_secrets_engines

- name: Gather facts
  include_tasks: facts.yml

- name: Tune engine's maximum TTL
  shell: "vault secrets tune -max-lease-ttl={{ item.config.max_lease_ttl }}h {{ item.path }}"
  environment:
    VAULT_ADDR: http://127.0.0.1:8200
    VAULT_TOKEN: "{{ vault_root_token }}"
  loop: "{{ vault_secrets_engines }}"
  no_log: true
  when: (vault_enabled_secrets_engines[item.path].config.max_lease_ttl | int) / 60 / 60 != item.config.max_lease_ttl
