---

- name: Pick a leader
  set_fact:
    vault_is_leader: "{{ ansible_play_hosts[0] == ansible_host }}"

- debug: msg="Selected {{ ansible_play_hosts[0] }} as the leader"
  run_once: true

- name: Read Vault status
  shell: vault status -format=json
  environment:
    VAULT_ADDR: http://127.0.0.1:8200
  register: vault_status_output
  failed_when: vault_status_output.rc not in [0, 1, 2]

- name: Set status facts
  set_fact:
    vault_is_initialized: "{{ (vault_status_output.stdout | from_json).initialized }}"
    vault_is_sealed: "{{ (vault_status_output.stdout | from_json).sealed  }}"

- name: Read enabled secret engines
  shell: vault secrets list -format=json
  environment:
    VAULT_ADDR: http://127.0.0.1:8200
    VAULT_TOKEN: "{{ vault_root_token }}"
  register: vault_enabled_secret_engines_output
  run_once: true
  when: vault_is_leader and vault_root_token

- name: Set enabled secrets engine facts
  set_fact:
    vault_enabled_secrets_engines: "{{ vault_enabled_secret_engines_output.stdout | from_json }}"
  when: vault_is_leader and vault_root_token
