---
# Provision Vault server

- name: Ensure enough servers are available to form a HA cluster
  assert:
    that: ansible_play_hosts | length >= 3
  run_once: true

- name: Install
  include_tasks: install.yml
  tags:
    - install

# using import_tasks rather than include_tasks to make sure
# ansible knows about our custom facts upfront
- name: Gather facts
  import_tasks: facts.yml
  tags:
    - always

- name: Configure
  include_tasks: configuration.yml
  tags:
    - install
    - configure

- name: Unseal
  include_tasks: unseal.yml
  when: vault_is_sealed
  tags:
    - install
    - unseal

- name: Enable secrets engines
  include_tasks: engines.yml
  when: vault_is_leader and vault_root_token and vault_secrets_engines
  tags:
    - install
    - engines
