---
# Installs Vault server

- name: Ensure required utilities are present
  apt:
    name:
      - curl
      - gnupg2
    state: latest
    update_cache: yes
  become: true

- name: Disable swap
  sysctl: name=vm.swappiness value=0
  become: true
  when: not vault_disable_mlock

- name: Resolve interface IP
  shell: ip -4 -o addr show {{ vault_bind }} scope global | awk 'NR=={{ vault_bind_seq }} {gsub(/\/.*/,"",$4); print $4}'
  register: vault_ip

- name: Import Hashicorp GPG key
  shell:
    cmd: "curl -fsSL {{ item.key }} | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/{{ item.keyring }} --import"
    creates: "/etc/apt/trusted.gpg.d/{{ item.keyring }}"
    warn: False
  with_items:
    - key: https://apt.releases.hashicorp.com/gpg
      keyring: hashicorp-archive-keyring.gpg
  become: true

- name: Fix key permissions
  file:
    path: "/etc/apt/trusted.gpg.d/{{ item }}"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  with_items:
    - hashicorp-archive-keyring.gpg
  become: true

- name: Add Hashicorp APT repository
  copy:
    content: >-
      deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main
    dest: /etc/apt/sources.list.d/kubernetes.list
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true

- name: Install latest version of Vault
  apt: name=vault state=latest update_cache=yes
  become: true

- name: Copy configuration
  template:
    src: templates/vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    owner: vault
    group: vault
    mode: 0640
  become: true
  notify:
    - Restart Vault

- name: Start Vault
  systemd: name=vault enabled=yes state=started daemon_reload=true
  become: true
