---
# Provision Vault server

- name: Install
  include_tasks: install.yml
  tags:
    - install

# using import_tasks rather than include_tasks to make sure
# ansible knows about our custom facts upfront
- name: Gather facts
  import_tasks: facts.yml
  tags:
    - always

- name: Configure
  include_tasks: configuration.yml
  tags:
    - install
    - configure

- name: Unseal
  include_tasks: unseal.yml
  when: vault_is_sealed
  tags:
    - install
    - unseal
