---
# Installs Gitea server

- name: Create group
  group: name="{{ gitea_group }}" state=present
  become: true

- name: Create user
  user:
    name: "{{ gitea_user }}"
    groups: "{{ gitea_group }}"
    shell: /bin/false
    create_home: true
    home: "/home/{{ gitea_user }}"
  become: true

- name: Install git
  apt: name=git state=latest update_cache=yes
  become: true

- name: Download and install Gitea
  get_url:
    url: https://dl.gitea.io/gitea/{{ gitea_version }}/gitea-{{ gitea_version }}-linux-amd64
    dest: /usr/local/sbin/gitea
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  become: true

- name: Copy service template
  template:
    src: templates/gitea.service.j2
    dest: /etc/systemd/system/gitea.service
    owner: root
    group: root
    mode: "u=rwx,g=rwx,o=rwx"
  become: true

- name: Create directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: 0750
  with_items:
    - "{{ gitea_working_directory }}/custom"
    - "{{ gitea_working_directory }}/data"
    - "{{ gitea_working_directory }}/log"
  become: true

- include_tasks: secrets.yml

- name: Create configuration directory
  file:
    path: /etc/gitea
    state: directory
    owner: root
    group: "{{ gitea_group }}"
    mode: 0755
  become: true

- name: Copy configuration
  template:
    src: templates/app.ini.j2
    dest: /etc/gitea/app.ini
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: 0600
  become: true
  notify:
    - Restart Gitea

- name: Start Gitea
  systemd: name=gitea enabled=yes state=restarted daemon_reload=true
  become: true
