---
# Provision Vault server

- name: Pick a leader
  set_fact:
    vault_is_leader: "{{ ansible_play_batch[0] == ansible_host }}"

- debug: msg="Selected {{ ansible_play_batch[0] }} as the leader"
  run_once: true

- name: Ensure enough servers are available to form a HA cluster
  assert:
    that: ansible_play_batch | length >= 3
  run_once: true

- name: Ensure TLS certificates have been provided if TLS is enabled
  assert:
    that: vault_agent_tls_cert_file and vault_agent_tls_key_file
  run_once: true
  when: not vault_agent_tls_disable

- name: Install
  include_tasks: install.yml
  tags:
    - install

# using import_tasks rather than include_tasks to make sure
# ansible knows about our custom facts upfront
- name: Gather facts
  import_tasks: facts.yml
  tags:
    - always

- name: Configure
  include_tasks: configuration.yml
  tags:
    - install
    - configure

- name: Unseal
  include_tasks: unseal.yml
  when: vault_is_sealed
  tags:
    - install
    - unseal
