---
# Installs CRI-O runtime

- name: Install GPG and friends
  apt:
    name:
      - curl
      - gnupg2
    state: latest
    update_cache: yes
  become: true

- name: Import kubic's GPG keys
  shell:
    cmd: "curl -fsSL {{ item.key }} | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/{{ item.keyring }} --import"
    creates: "/etc/apt/trusted.gpg.d/{{ item.keyring }}"
    warn: False
  with_items:
    - key: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_{{ ansible_lsb.major_release }}/Release.key"
      keyring: kubic-archive-libcontainers-keyring.gpg
    - key: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ kubernetes_cri_o_version }}/Debian_{{ ansible_lsb.major_release }}/Release.key"
      keyring: kubic-archive-cri-o-keyring.gpg
  become: true

- name: Fix key permissions
  file:
    path: "/etc/apt/trusted.gpg.d/{{ item }}"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  with_items:
    - kubic-archive-libcontainers-keyring.gpg
    - kubic-archive-cri-o-keyring.gpg
  become: true

- name: Add kubic's libcontainers APT repository
  copy:
    content: >-
      deb [signed-by=/etc/apt/trusted.gpg.d/kubic-archive-libcontainers-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_{{ ansible_lsb.major_release }}/ /
    dest: /etc/apt/sources.list.d/kubic-libcontainers.list
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true

- name: Add kubic's cri-o APT repository
  copy:
    content: >-
      deb [signed-by=/etc/apt/trusted.gpg.d/kubic-archive-cri-o-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ kubernetes_cri_o_version }}/Debian_{{ ansible_lsb.major_release }}/ /
    dest: /etc/apt/sources.list.d/kubic.cri-o.list
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true

- name: Install CRI-O runtime
  apt:
    name:
      - cri-o
      - cri-o-runc
      - cri-tools
    state: latest
    update_cache: yes
  become: true

- name: Copy configuration
  template: src=crio.conf.j2 dest=/etc/crio/crio.conf
  become: true
  notify:
    - Restart CRI-O

- name: Copy crictl config
  template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml
    owner: root
    mode: 0644
  become: true

- name: Enable and start CRI-O service
  service: name=crio enabled=yes state=started
  become: true
